Just VMEM.

diff --git a/src/test/RUNTESTS b/src/test/RUNTESTS
--- a/src/test/RUNTESTS
+++ b/src/test/RUNTESTS
@@ -469,17 +469,17 @@ verbose_tests=
 [ -n "$KEEP_GOING" ] && keep_going=$KEEP_GOING
 [ -n "$VERBOSE_TESTS" ] && verbose_tests="$VERBOSE_TESTS"
 
-
-PMEMDETECT="tools/pmemdetect/pmemdetect.static-nondebug"
-
-if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ]; then
-	if $PMEMDETECT -s $PMEM_FS_DIR; then
-		echo "error: PMEM_FS_DIR_FORCE_PMEM variable is set but PMEM_FS_DIR [" $PMEM_FS_DIR  "] supports MAP_SYNC"
-		echo "Setting this flag prevents from testing an integration between pmem_map_file and pmem_is_pmem."
-		echo "If you want to ignore this error, please set PMEM_FS_DIR_FORCE_PMEM=2."
-		exit 1
-	fi
-fi
+#XXX
+#PMEMDETECT="tools/pmemdetect/pmemdetect.static-nondebug"
+#
+#if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ]; then
+#	if $PMEMDETECT -s $PMEM_FS_DIR; then
+#		echo "error: PMEM_FS_DIR_FORCE_PMEM variable is set but PMEM_FS_DIR [" $PMEM_FS_DIR  "] supports MAP_SYNC"
+#		echo "Setting this flag prevents from testing an integration between pmem_map_file and pmem_is_pmem."
+#		echo "If you want to ignore this error, please set PMEM_FS_DIR_FORCE_PMEM=2."
+#		exit 1
+#	fi
+#fi
 
 if [ -v PMEM_FS_DIR ] && [ ! -d "$PMEM_FS_DIR" ]; then
 	echo "error: PMEM_FS_DIR=$PMEM_FS_DIR doesn't exist"
@@ -491,28 +491,28 @@ if [ -v NON_PMEM_FS_DIR ] && [ ! -d "$NON_PMEM_FS_DIR" ]; then
 	exit 1
 fi
 
-if [ -d "$PMEM_FS_DIR" ]; then
-	if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ] || [ "$PMEM_FS_DIR_FORCE_PMEM" = "2" ]; then
-		PMEM_IS_PMEM=0
-	else
-		$PMEMDETECT "$PMEM_FS_DIR"
-		PMEM_IS_PMEM=$?
-	fi
+#if [ -d "$PMEM_FS_DIR" ]; then
+#	if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ] || [ "$PMEM_FS_DIR_FORCE_PMEM" = "2" ]; then
+#		PMEM_IS_PMEM=0
+#	else
+#		$PMEMDETECT "$PMEM_FS_DIR"
+#		PMEM_IS_PMEM=$?
+#	fi
+#
+#	if [ $PMEM_IS_PMEM -ne 0 ]; then
+#		echo "error: PMEM_FS_DIR=$PMEM_FS_DIR does not point to a PMEM device"
+#		exit 1
+#	fi
+#fi
 
-	if [ $PMEM_IS_PMEM -ne 0 ]; then
-		echo "error: PMEM_FS_DIR=$PMEM_FS_DIR does not point to a PMEM device"
-		exit 1
-	fi
-fi
-
-if [ -d "$NON_PMEM_FS_DIR" ]; then
-	$PMEMDETECT "$NON_PMEM_FS_DIR"
-	NON_PMEM_IS_PMEM=$?
-	if [ $NON_PMEM_IS_PMEM -eq 0 ]; then
-		echo "error: NON_PMEM_FS_DIR=$NON_PMEM_FS_DIR does not point to a non-PMEM device"
-		exit 1
-	fi
-fi
+#if [ -d "$NON_PMEM_FS_DIR" ]; then
+#	$PMEMDETECT "$NON_PMEM_FS_DIR"
+#	NON_PMEM_IS_PMEM=$?
+#	if [ $NON_PMEM_IS_PMEM -eq 0 ]; then
+#		echo "error: NON_PMEM_FS_DIR=$NON_PMEM_FS_DIR does not point to a non-PMEM device"
+#		exit 1
+#	fi
+#fi
 
 #
 # command-line argument processing...
