test: verify test dirs once per RUNTESTS execution
Do not check if PMEM_FS_DIR is pmem and NON_PMEM_FS_DIR is not pmem for
evey single require_fs_type execution but once per RUNTESTS[.PS1]. This
couse the pmemdetect is invoked less frequently and should positively
impact overall test execution time.

diff --git a/src/test/RUNTESTS b/src/test/RUNTESTS
--- a/src/test/RUNTESTS
+++ b/src/test/RUNTESTS
@@ -451,6 +451,29 @@ if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ]; then
 	fi
 fi
 
+if [ -d "$PMEM_FS_DIR" ]; then
+	if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ] || [ "$PMEM_FS_DIR_FORCE_PMEM" = "2" ]; then
+		PMEM_IS_PMEM=0
+	else
+		$PMEMDETECT "$PMEM_FS_DIR"
+		PMEM_IS_PMEM=$?
+	fi
+
+	if [ $PMEM_IS_PMEM -ne 0 ]; then
+		echo "error: PMEM_FS_DIR=$PMEM_FS_DIR does not point to a PMEM device"
+		exit 1
+	fi
+fi
+
+if [ -d "$NON_PMEM_FS_DIR" ]; then
+	$PMEMDETECT "$NON_PMEM_FS_DIR"
+	NON_PMEM_IS_PMEM=$?
+	if [ $NON_PMEM_IS_PMEM -eq 0 ]; then
+		echo "error: NON_PMEM_FS_DIR=$NON_PMEM_FS_DIR does not point to a non-PMEM device"
+		exit 1
+	fi
+fi
+
 #
 # command-line argument processing...
 #
