test: disable PMEM_FS_DIR_FORCE_PMEM on PMEM fs
If PMEM_FS_DIR_FORCE_PMEM is set to 1 the pmem_is_pmem will not check
if the mapping has been created with MAP_SYNC. This patch reports an
error if this variable is set to 1 AND the PMEM_FS_DIR supports
MAP_SYNC.

diff --git a/src/test/RUNTESTS b/src/test/RUNTESTS
--- a/src/test/RUNTESTS
+++ b/src/test/RUNTESTS
@@ -439,6 +439,18 @@ verbose_tests=
 [ -n "$KEEP_GOING" ] && keep_going=$KEEP_GOING
 [ -n "$VERBOSE_TESTS" ] && verbose_tests="$VERBOSE_TESTS"
 
+
+PMEMDETECT="tools/pmemdetect/pmemdetect.static-nondebug"
+
+if [ "$PMEM_FS_DIR_FORCE_PMEM" = "1" ]; then
+	if $PMEMDETECT -s $PMEM_FS_DIR; then
+		echo "error: PMEM_FS_DIR_FORCE_PMEM variable is set but PMEM_FS_DIR [" $PMEM_FS_DIR  "] supports MAP_SYNC"
+		echo "Setting this flag prevents from testing an integration between pmem_map_file and pmem_is_pmem."
+		echo "If you want to ignore this error, please set PMEM_FS_DIR_FORCE_PMEM=2."
+		exit 1
+	fi
+fi
+
 #
 # command-line argument processing...
 #
