pmemobj: fix condition variable test
The test could fail randomly on a race condition on file output. Add
line count check to verify if mock failed to initialize each
synchronization primitive.

diff --git a/src/test/obj_sync/TEST3 b/src/test/obj_sync/TEST3
--- a/src/test/obj_sync/TEST3
+++ b/src/test/obj_sync/TEST3
@@ -51,4 +51,11 @@ expect_normal_exit valgrind --log-file=valgrind$UNITTEST_NUM.log --tool=drd\
 
 check
 
+ERR_FILE=err3.log
+if [ `wc -l < $ERR_FILE` -ne 1 ];
+    then
+        echo "error: $CHECK_LOG_FILE match failed"
+        exit 1
+fi
+
 pass
