pmempool: add tests

diff --git a/src/test/pmempool_info/TEST8 b/src/test/pmempool_info/TEST8
--- a/src/test/pmempool_info/TEST8
+++ b/src/test/pmempool_info/TEST8
@@ -1,3 +1,5 @@
+#!/bin/bash -e
+#
 # Copyright (c) 2014-2015, Intel Corporation
 #
 # Redistribution and use in source and binary forms, with or without
@@ -28,33 +30,45 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# Makefile -- top Makefile for tools
 #
+# pmempool_info/TEST8 -- test for info command
+#
+export UNITTEST_NAME=pmempool_info/TEST8
+export UNITTEST_NUM=8
 
-TARGETS = pmempool
-SCOPEDIRS=$(TARGETS)
-SCOPEFILES=$(foreach dir, $(SCOPEDIRS), $(shell find $(dir) -name *.[ch] ))
+. ../unittest/unittest.sh
 
-all    : TARGET = all
-check  : TARGET = check
-test   : TARGET = test
-clean  : TARGET = clean
-clobber: TARGET = clobber
-cstyle : TARGET = cstyle
-install: TARGET = install
+require_fs_type pmem non-pmem
+require_build_type nondebug
 
-all clean clobber cstyle install check test: $(TARGETS)
+setup
 
-$(TARGETS):
-	$(MAKE) -C $@ $(TARGET)
+POOL=$DIR/file.pool
+LOG=out${UNITTEST_NUM}.log
+rm -rf $LOG && touch $LOG
 
-clean:
-	$(RM) TAGS cscope.in.out cscope.out cscope.po.out
+rm -rf $POOL
+expect_normal_exit $PMEMPOOL create blk 512 $POOL
+expect_normal_exit $PMEMWRITE $POOL 1:e 2:w:TEST
 
-clobber: clean
+INFO_NLBA=$(expect_normal_exit $PMEMPOOL info $POOL | grep 'External LBA count' | grep -o '[0-9]\+')
+NLBA=$(expect_normal_exit $PMEMPOOL info -m $POOL | grep '[0-9]\+: 0x[0-9]\+.*' | wc -l)
+NZER=$(expect_normal_exit $PMEMPOOL info -mue $POOL | grep '[0-9]\+: 0x[0-9]\+.*' | wc -l)
+NERR=$(expect_normal_exit $PMEMPOOL info -muz $POOL | grep '[0-9]\+: 0x[0-9]\+.*' | wc -l)
+NNON=$(expect_normal_exit $PMEMPOOL info -mez $POOL | grep '[0-9]\+: 0x[0-9]\+.*' | wc -l)
 
-cscope:
-	cscope -q -b $(SCOPEFILES)
-	ctags -e $(SCOPEFILES)
+echo "Number of LBAs: $INFO_NLBA" >> $LOG
+echo "Number of LBAs in map: $NLBA" >> $LOG
+echo "Number of LBAs [zero]: $NZER" >> $LOG
+echo "Number of LBAs [error]: $NERR" >> $LOG
+echo "Number of LBAs [no flag]: $NNON" >> $LOG
 
-.PHONY: all clean clobber cstyle install common cscope $(TARGETS)
+NSUM=$(($NZER + $NERR + $NNON))
+[[ $NSUM == $NLBA ]] || $(echo "$NSUM != $NLBA" && exit 1)
+[[ $NSUM == $INFO_NLBA ]] || $(echo "$NSUM != $INFO_NLBA" && exit 1)
+
+expect_normal_exit $PMEMPOOL info -dz $POOL >> $LOG
+
+check
+
+pass
