pmem: add functions to handle unsafe shutdowns

diff --git a/src/test/pmem_sds/TEST7 b/src/test/pmem_sds/TEST7
--- a/src/test/pmem_sds/TEST7
+++ b/src/test/pmem_sds/TEST7
@@ -1,3 +1,5 @@
+#!/usr/bin/env bash
+#
 # Copyright 2017, Intel Corporation
 #
 # Redistribution and use in source and binary forms, with or without
@@ -28,23 +30,40 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #
-# src/pmemcommon.inc -- common SOURCE definitions for NVM pmem libraries
+
 #
+# src/test/pmem_sds/TEST7 -- unittest for shutdown state
+#
+export UNITTEST_NAME=pmem_sds/TEST7
+export UNITTEST_NUM=7
 
-osdep = $(1)_$(shell uname -s | tr "[:upper:]" "[:lower:]")$(2)
+# standard unit test setup
+. ../unittest/unittest.sh
 
-SOURCE =\
-	$(COMMON)/file.c\
-	$(COMMON)/file_linux.c\
-	$(COMMON)/mmap.c\
-	$(COMMON)/mmap_linux.c\
-	$(COMMON)/os_linux.c\
-	$(COMMON)/os_thread_linux.c\
-	$(COMMON)/os_ras_linux.c\
-	$(COMMON)/out.c\
-	$(COMMON)/pool_hdr.c\
-	$(COMMON)/set.c\
-	$(COMMON)/util.c\
-	$(COMMON)/uuid.c\
-	$(COMMON)/$(call osdep, uuid,.c)\
-	$(COMMON)/util_linux.c
+require_test_type medium
+
+require_fs_type any
+
+require_build_type debug
+
+setup
+
+PMEM_LOG_LEVEL=3
+
+# fail after an open flag is set
+expect_normal_exit ./pmem_sds 1 7 \
+				   $DIR/testfile1 5 0 \
+				   $DIR/testfile2 7 0 \
+				   $DIR/testfile3 9 0
+
+# adr failure - USC was incremented
+expect_abnormal_exit ./pmem_sds 0 0 \
+				   $DIR/testfile1 5 0 \
+				   $DIR/testfile2 7 1 \
+				   $DIR/testfile3 9 0
+
+grep "pmem_check_shutdown_state" pmem$UNITTEST_NUM.log > grep$UNITTEST_NUM.log || true
+
+check
+
+pass
