test: confirm '-' on end of log name appends PID

diff --git a/src/test/traces/TEST0 b/src/test/traces/TEST0
--- a/src/test/traces/TEST0
+++ b/src/test/traces/TEST0
@@ -45,11 +45,20 @@ require_build_type debug
 
 setup
 
+shopt -u failglob
+rm -f ./custom_file.log-*
+shopt -s failglob
+
 export TRACE_LOG_LEVEL=4
-export TRACE_LOG_FILE=./custom_file.log
+export TRACE_LOG_FILE=./custom_file.log-
 expect_normal_exit ./traces$EXESUFFIX
 
 # check results
+[ -s ./custom_file.log-* ] || {
+	echo "error: ./custom_file.log-PID not found"
+	exit 1
+}
+mv ./custom_file.log-* custom_file.log
 ../match custom_file.log.match
 
 pass
