common: add windows build to GitHub Actions

diff --git a/.github/workflows/gha.yml b/.github/workflows/gha.yml
--- a/.github/workflows/gha.yml
+++ b/.github/workflows/gha.yml
@@ -13,19 +13,19 @@ on: [push, pull_request]
 env:
     GITHUB_REPO:    pmem/pmdk
     DOCKERHUB_REPO: pmem/pmdk
-    HOST_WORKDIR:   /home/runner/work/pmdk/pmdk
-    WORKDIR:        utils/docker
-    # global variables
-    PMDK_CC:        gcc
-    PMDK_CXX:       g++
-    MAKE_PKG:       0
-    REMOTE_TESTS:   0
-    VALGRIND:       1
 
 jobs:
-  build:
-    name: Build
+  linux:
+    name: Linux
     runs-on: ubuntu-latest
+    env:
+      HOST_WORKDIR:   /home/runner/work/pmdk/pmdk
+      WORKDIR:        utils/docker
+      PMDK_CC:        gcc
+      PMDK_CXX:       g++
+      MAKE_PKG:       0
+      REMOTE_TESTS:   0
+      VALGRIND:       1
     strategy:
       matrix:
         CONFIG: ["N=1 OS=ubuntu OS_VER=19.10 FAULT_INJECTION=1 TEST_BUILD=debug",
@@ -54,3 +54,87 @@ jobs:
 
        - name: Push the image
          run: cd $WORKDIR && source ./set-vars.sh && ${{ matrix.CONFIG }} /bin/bash -c "if [[ -f XXX_DISABLE_${CI_FILE_PUSH_IMAGE_TO_REPO} ]]; then images/push-image.sh $OS-$OS_VER; fi"
+
+  windows:
+    name: Windows
+    runs-on: windows-latest
+    env:
+      platform: x64
+      solutionname: PMDK.sln
+      ex_solutionname: Examples.sln
+      msbuild: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
+      # Platform Toolset for Visual Studio 2019
+      platform_toolset: "v142"
+      perl: "C:\\Strawberry\\perl\\bin"
+    strategy:
+      matrix:
+        CONFIG: [Debug, Release]
+    steps:
+       - name: Update Path
+         run: |
+           echo "::add-path::$Env:msbuild"
+           echo "::add-path::$Env:perl"
+
+       - name: Clone the git repo
+         uses: actions/checkout@v1
+
+       - name: Various debug checks (cstyle, whitespace etc.)
+         run: |
+           if ("${{ matrix.CONFIG }}" -eq "Debug")
+           {
+              Install-Module PsScriptAnalyzer -Force
+              utils/CSTYLE.ps1
+              if ($LASTEXITCODE -ne 0) {
+                 exit 1
+              }
+              utils/CHECK_WHITESPACE.ps1
+              if ($LASTEXITCODE -ne 0) {
+                 exit 1
+              }
+              utils/ps_analyze.ps1
+              if ($LASTEXITCODE -ne 0) {
+                 exit 1
+              }
+              perl utils/sort_solution check
+              if ($LASTEXITCODE -ne 0) {
+                 exit 1
+              }
+              ./utils/check_sdk_version.py -d .
+              if ($LASTEXITCODE -ne 0) {
+                 exit 1
+              }
+           }
+
+       - name: Build
+         run: |
+           msbuild src\$Env:solutionname -property:Configuration=${{ matrix.CONFIG }},PlatformToolset=$Env:platform_toolset -m -v:m
+           msbuild src\examples\$Env:ex_solutionname -property:Configuration=${{ matrix.CONFIG }},PlatformToolset=$Env:platform_toolset -m -v:m
+
+       - name: Create ZIP archive
+         run: utils/CREATE-ZIP.ps1 -b ${{ matrix.CONFIG }}
+
+       - name: Run tests
+         shell: powershell
+         run: |
+           if ($true) {
+               cd src\test
+               echo "`$Env:NON_PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
+               echo "`$Env:PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
+               echo "`$Env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
+               echo "`$Env:PMDK_NO_ABORT_MSG = `"1`"" >> testconfig.ps1
+               echo "`$Env:TM = `"1`"" >> testconfig.ps1
+               write-output "config = {'unittest_log_level': 1, 'pmem_fs_dir': 'C:\\temp', 'non_pmem_fs_dir': 'C:\\temp', 'tm': True, 'test_type': 'check', 'fs': 'all', 'fs_dir_force_pmem': 1, 'keep_going': False, 'timeout': '4m', 'build': 'debug', 'force_enable': None}" | out-file "testconfig.py" -encoding utf8
+
+               if ("${{ matrix.CONFIG }}" -eq "Debug") {
+                   ./RUNTESTS.ps1 -b debug -o 4m
+                   if ($?) {
+                       ./RUNTESTS.py -b debug
+                   }
+               }
+               if ("${{ matrix.CONFIG }}" -eq "Release") {
+                   ./RUNTESTS.ps1 -b nondebug -o 4m
+                   if ($?) {
+                       ./RUNTESTS.py -b release
+                   }
+               }
+           }
